name: Manual workflow

on:
  push:
    branches:
      - master
      - test

jobs:
  connect:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
        env:
          MYSQL_ROOT_PASSWORD: test

    steps:
    - uses: actions/checkout@v1
    - name: run mysql
      run: sudo /etc/init.d/mysql start
